### ISSUE TITLE
'memory_limit_in_mb' error from lambda_function.py

### ISSUE THREAD

**Issue by abtreece** [logzio/cloudwatch-logs-shipper-lambda#10]
Current lambda results in the following error when configured as instructed.  Removing line #39 resolves the error

```
'memory_limit_in_mb': KeyError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 77, in lambda_handler
_parse_cloudwatch_log(log, aws_logs_data)
File "/var/task/lambda_function.py", line 39, in _parse_cloudwatch_log
log['memory_limit_in_mb'] = aws_logs_data['memory_limit_in_mb']
KeyError: 'memory_limit_in_mb'
```

**Comment by abtreece** [comment]
disregard... this line was removed prior to the opening of this issue.
